-- MySQL Script generated by MySQL Workbench
-- Fri Jan 19 13:00:06 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bdCurrculum
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bdCurrculum
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdCurrculum` ;
USE `bdCurrculum` ;

-- -----------------------------------------------------
-- Table `bdCurrculum`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdCurrculum`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `ativo` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdCurrculum`.`pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdCurrculum`.`pessoa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `foto` TINYTEXT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `nacionalidade` VARCHAR(45) NOT NULL,
  `estadoCivil` VARCHAR(45) NOT NULL,
  `dNasc` DATE NOT NULL,
  `rua` VARCHAR(100) NOT NULL,
  `numero` VARCHAR(10) NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `uf` CHAR(2) NOT NULL,
  `cep` VARCHAR(9) NOT NULL,
  `tel1` VARCHAR(15) NOT NULL,
  `tel2` VARCHAR(15) NULL,
  `email` VARCHAR(70) NULL,
  `objetivo` LONGTEXT NOT NULL,
  `habilidade` LONGTEXT NOT NULL,
  `formacao` LONGTEXT NOT NULL,
  `experiencia` LONGTEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
